version: '3.9'
services:
  web:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    image: workshop-container:v0.1
    environment:
      - PORT=8020
    env_file:
      - .env
    ports:
      - "8080:8020"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"

  postgres_db:
    image: postgres
    command: -p 5432
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
