# Generated by Django 3.0.1 on 2022-09-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('skill', models.CharField(choices=[('Beginner', 'BEGINNER'), ('Intermediate', 'INTERMEDIATE'), ('Pro', 'PRO')], default='Beginner', max_length=15)),
            ],
        ),
    ]
